[package]
name = "passwordstore"
description = "A modern Rust-based password manager for Linux, built with GTK4/Libadwaita"
authors = ["noobping"]
version = "0.1.1"
edition = "2021"

[features]
setup = []
libripasso = ["ripasso"]

[dependencies]
anyhow = "^1.0"
thiserror = "^2.0"
gtk4 = { version = "^0.10", package = "gtk4" }
adw = { version = "^0.8.0", package = "libadwaita", features = ["v1_8"] }
walkdir = "^2.5.0"
toml = "^0.9.8"
serde = { version = "^1.0.228", features = ["derive"] }
ripasso = { version = "^0.8.0", optional = true}
dirs = "6.0.0"

[build-dependencies]
glib-build-tools = "^0.21.0"
