name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            gcc \
            libadwaita-1-0 \
            libadwaita-1-dev \
            libcairo2-dev \
            libglib2.0-dev \
            libgpg-error-dev \
            libgpgme-dev \
            libgtk-4-dev \
            libpango1.0-dev \
            librust-libadwaita-dev \
            librust-libadwaita-sys-dev \
            libssl-dev \
            nettle-dev \
            pkg-config
      - name: Build
        run: cargo build --verbose --release --features setup
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: passwordstore.${{ matrix.target }}
          path: target/${{ matrix.target }}/release/passwordstore
